drop table if exists user_role;
drop table if exists users;

create table users(
    id int generated by default as identity primary key,
    name varchar not null,
    email varchar not null,
    password varchar not null
);

create table user_role
(
    user_id int     not null,
    role    varchar not null,
    constraint user_roles_idx unique (user_id, role),
    foreign key (user_id) references users (id) on delete cascade
);